routes/web.php
        Route::resource('/faqs', 'Backend\FaqController');
        Route::resource('/comissions', 'Backend\CommisionsController');
        Route::resource('/category-blogs', 'Backend\BlogCategoryController');
        Route::resource('/testimonial', 'Backend\TestimonialController', [
            'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
        ]);
        Route::resource('/banner', 'Backend\BannerController', [
            'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
        ]);
        Route::resource('/managing-parteners', 'Backend\ManagingPartenerController');
        Route::resource('/membership-details', 'Backend\MembershipDetailsController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/memberships', 'Backend\MembershipController', [
            'only' => ['index', 'edit', 'update']
        ]);

        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);


        Route::get('/discounts', 'Backend\DiscountController@index')->name('discount.index');
        Route::resource('/coupons', 'Backend\CouponController');

        Route::resource('/first-order-discount', 'Backend\FirstOrderDisountController', [
            'only' => ['edit', 'update']
        ]);

        Route::resource('/memberships-discount', 'Backend\MembershipDisountController', [
            'only' => ['edit', 'update']
        ]);

        Route::resource('/referral-discount', 'Backend\ReferralDisountController', [
            'only' => ['edit', 'update']
        ]);

        Route::get('/user-referrals', 'Backend\ReferralController@index')->name('user.referral.index');

        //User Order History

        Route::get('/order-history', 'Backend\OrderController@index')->name('get.order.history');
        Route::get('/order/create', 'Backend\OrderController@create')->name('order.create');
        Route::post('/order/store', 'Backend\OrderController@store')->name('order.store');
        Route::get('/order/{id}', 'Backend\OrderController@showOrder')->name('get.user.order.show');
        Route::get('/order/edit/{id}', 'Backend\OrderController@editOrder')->name('get.user.order.edit');
        Route::post('/order/update', 'Backend\OrderController@updateOrder')->name('order.update');
        Route::get('/order/delete/{id}', 'Backend\OrderController@destroy')->name('get.user.order.delete');
        Route::post('/order/updatepayment', 'Backend\AjaxController@updatePaymentStatus')->name('order.updatePaymentStatus');
        Route::post('/order/uploadpaymentslipbyadmin', 'Backend\OrderController@uploadpaymentslipbyadmin')->name('order.uploadpaymentslipbyadmin');


        //Assign Driver

        Route::get('/driver', 'Backend\StaffController@index')->name('get.employee.user');


        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/termsandconditions', 'Backend\TermsAndConditionController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');

        Route::resource('/ledger', 'Backend\LedgerController');
        Route::resource('/wallet', 'Backend\WalletController');
        Route::resource('/notification', 'Backend\NotificationController');
        Route::get('/staff_order/{id}', 'Backend\WalletController@staffOrder')->name('get.user.staffOrder');

        Route::post('/storepayment', 'Backend\WalletController@storepayment')->name('storepayment');
        Route::resource('/payment', 'Backend\PaymentController');
        Route::post('/providerpaymentverify', 'Backend\AjaxController@providerpaymentverify')->name('providerpaymentverify');
    });
    //route for referral code
    Route::get('/referral-code', 'Backend\SendReferralCodeController@index')->name('referral-code.index');
    Route::post('/referral-code/send', 'Backend\SendReferralCodeController@sendCodeWithEmail')->name('referral-code.send');
    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');


    //Customer Routes
    Route::prefix('customer')->name('customer.')->group(function () {
        Route::get('/dashboard', 'Customer\MainController@index')->name('dashboard.index');
        Route::post('/coupons', 'Customer\CouponController@store')->name('coupons.store');
        Route::delete('/coupons', 'Customer\CouponController@destroy')->name('coupons.destroy');


        //User Profiles
        Route::get('profile', 'Customer\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Customer\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Customer\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Customer\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Customer\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Customer\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Customer\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Customer\ProfileController@updateMobileNumber')->name('update.user.phone');


        //User Referrals
        Route::get('referrals', 'Customer\ReferralController@index')->name('user.referral');


        //User Order History

        Route::get('/order-history', 'Customer\OrderController@index')->name('order.history');
        Route::get('/order/{id}', 'Customer\OrderController@showOrder')->name('user.order.show');
        Route::resource('/notification', 'Customer\NotificationController');
    });


    //Staff Routes
    Route::prefix('staff')->name('staff.')->group(function () {
        Route::get('/dashboard', 'ServiceProvider\DashboardController@index')->name('dashboard.index');


        //staff Profiles
        Route::get('profile', 'ServiceProvider\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'ServiceProvider\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'ServiceProvider\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'ServiceProvider\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'ServiceProvider\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'ServiceProvider\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'ServiceProvider\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'ServiceProvider\ProfileController@updateMobileNumber')->name('update.user.phone');


        //Staff Appointment History

        Route::get('/appointment-history', 'ServiceProvider\OrderController@index')->name('appointment.history');
        Route::get('/appointment/{id}', 'ServiceProvider\OrderController@showOrder')->name('user.appointment.show');


        //Staff Order Status
        Route::post('update-order-staff-status', 'ServiceProvider\OrderController@updateOrderStaffStatus')->name('update.order.staff.status');
        Route::post('update-order-progress-status', 'ServiceProvider\OrderController@updateOrderProgressStatus')->name('update.order.progress.status');
        Route::resource('/ledger', 'ServiceProvider\LedgerController');
        Route::resource('/wallet', 'ServiceProvider\WalletController');
        Route::resource('/notification', 'ServiceProvider\NotificationController');
        Route::get('/company_order/{id}', 'ServiceProvider\WalletController@companyOrder')->name('get.user.companyOrder');
        Route::post('/sendpayment', 'ServiceProvider\WalletController@sendpayment')->name('sendpayment');


    });


    // User Dairy
    Route::get('/user/dairy/{id}', 'DairyController@index')->name('user.dairy.index');
    Route::get('/user/dairy/create/{id}', 'DairyController@create')->name('user.dairy.create');
    Route::post('/user/dairy/store', 'DairyController@store')->name('user.dairy.store');
    Route::get('/user/dairy/detail/{id}', 'DairyController@show')->name('user.dairy.show');


});


//Route::middleware(['private-directory'])->group(function () {
//Landing Page Routes

Route::get('services', 'Frontend\ServiceController@index')->name('service');
Route::get('services/{category}/{slug}', 'Frontend\ServiceController@serviceItems')->name('service.items');
Route::get('special-offer/{slug}', 'Frontend\BlogController@getBlog')->name('blog.show');
Route::get('special-offers', 'Frontend\BlogController@index')->name('blog');

app/Http/Controllers/Backend/ProfileController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Area;
use App\Models\City;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {

        $user = auth()->user();
        return view('backend.profiles.index', compact('user'));
    }

    public function editProfile()
    {

        $user = auth()->user();
        $categories = Category::all();
        $cities = City::all();
        $areas = Area::all();
        return view('backend.profiles.edit-profile', compact('user', 'categories', 'cities', 'areas'));
    }

    public function updateProfile(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'city_id' => 'required|integer',
            'area_id' => 'required|integer',
            'category_id' => 'required|integer',
            'age' => 'required',
            'cnic' => 'required',
            'address' => 'required',
            'email' => 'required|string|email|max:255',
        ], [
            'first_name.required' => 'First name  is required.',
            'last_name.required' => 'Last name  is required.',
            'city_id.required' => 'City is required.',
            'area_id.required' => 'Area  is required.',
            'category_id.required' => 'Gender  is required.',
            'age.required' => 'Age  is required.',
            'cnic.required' => 'CNIC  is required.',
            'email.required' => 'Email  is required.',
        ]);

        $user = User::find(auth()->user()->id);

        $user->update([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'city_id' => $request->get('city_id'),
            'area_id' => $request->get('area_id'),
            'category_id' => $request->get('category_id'),
            'age' => $request->get('age'),
            'cnic' => $request->get('cnic'),
            'address' => $request->get('address'),
            'email' => $request->get('email'),
        ]);

        return redirect()->route('admin.profile.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Profile updated successfully.'
            ]);
    }

    public function editProfileImage(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());
        $user = User::where('id', $request->user_id)->first();

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/user_profiles');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $profile_image ='https://familyfriend.com.pk/uploads/user_profiles/' . $name;
        } else {
            $profile_image = $user->profile_pic;
        }
        $user->update([
            'profile_pic' => $profile_image,
        ]);

        $response['status'] = 'success';
        $response['message'] = 'Profile Image updated successfully.';

        return $response;


    }

    public function changePassword()
    {

        $user = auth()->user();
        return view('backend.profiles.change-password', compact('user'));
    }

    public function changeMobileNumber()
    {

        $user = auth()->user();
        return view('backend.profiles.change-mobile-number', compact('user'));
    }

    public function updateMobileNumber(Request $request)
    {
        $this->validate($request, [
            'phone_number' => 'required',
        ], [
            'phone_number.required' => 'Mobile Number is required.',

        ]);

        $user = User::find(auth()->user()->id);

        $user->update([
            'phone_number' => $request->get('phone_number'),
        ]);

        return redirect()->route('admin.profile.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Mobile Number updated successfully.'
            ]);
    }

    public function updatePassword(Request $request)
    {
        if (!(Hash::check($request->get('current-password'), auth()->user()->password))) {
            // The passwords matches
            return redirect()->back()->with("error", "Your current password does not matches with the password you provided. Please try again.");
        }

        if (strcmp($request->get('current-password'), $request->get('new-password')) == 0) {
            //Current password and new password are same
            return redirect()->back()->with("error", "New Password cannot be same as your current password. Please choose a different password.");
        }

        $validatedData = $request->validate([
            'current-password' => 'required',
            'new-password' => 'required|string|min:6',
        ]);

        if (strcmp($request->get('new-password-confirm'), $request->get('new-password')) == 0) {
            //Change Password
            $user = Auth::user();
            $user->password = bcrypt($request->get('new-password'));
            $user->save();

            return redirect()->route('admin.profile.index')
                ->with([
                    'flash_status' => 'success',
                    'flash_message' => 'Password Changed successfully.'
                ]);

        } else {
            return redirect()->back()->with("error", "New Password must be same as your confirm password.");
        }


    }
}

app/Http/Controllers/Customer/MainController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:customer');
    }

    public function index()
    {
        $total_orders = Order::where('customer_id', auth()->user()->id)->get()->count();
        $pending_orders = Order::where('order_status', 'pending')->where('customer_id', auth()->user()->id)->get()->count();
        $completed_orders = Order::where('order_status', 'completed')->where('customer_id', auth()->user()->id)->get();
        $confirmed_orders = Order::where('order_status', 'confirmed')->where('customer_id', auth()->user()->id)->get();
        return view('customer.dashboard.index', compact('total_orders', 'pending_orders', 'completed_orders','confirmed_orders'));
    }
}

app/Http/Controllers/Customer/NotificationController.php
<?php

namespace App\Http\Controllers\Customer;


use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Notification;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Auth;
class NotificationController extends Controller
{

    public function index()
    {
        $notifications = Notification::where('user_id',Auth::user()->id)->get();
        return view('customer.notification.index', compact('notifications'));
    }

    
}

resources/views/customer/profiles/change-mobile-number.blade.php
@extends('customer.main')
@section('title','Profile')
@push('css')
    <style>
        .serviceInner {
            height: 280px;
        }

        .bannerFields {
            margin-top: 15px;
        }
    </style>
@endpush
@section('content')
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="">
                <div class="">
                    <div class="m-portlet">
                        <div class="container">
                            <div class="m-portlet__body">
                                <div class="serviceBoxMain">
                                    <div class="serverInnerDetails">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-6 col-xs-12 bannerFields">
                                                <form action="{{ route('customer.update.user.phone') }}"
                                                      method="post" enctype="multipart/form-data">
                                                    @csrf
                                                    <div class="row">
                                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                                            <div class="form-group">
                                                                <label for="phone_number">Enter New Mobile
                                                                    Number</label>
                                                                <input type="tel" class="form-control"
                                                                       name="phone_number" id="phone_number"
                                                                       placeholder="03001234567" pattern="[03]{2}[0-9]{9}"
                                                                       title="Phone number with 03 and remaing 9 digit with 0-9"
                                                                       value="{{ $user->phone_number }}">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-md-12 col-sm-12 col-xs-12 text-right">
                                                            <a href="{{ route('customer.profile.index') }}"
                                                               class="btn buttonMain hvr-bounce-to-right">
                                                                Cancel
                                                            </a>
                                                            <button type="submit"
                                                                    class="btn buttonMain hvr-bounce-to-right">Save
                                                                Changes
                                                            </button>
                                                        </div>
                                                    </div>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>

    </script>
@endpush

resources/views/customer/profiles/index.blade.php
@extends('customer.main')
@section('title','Profile')
@push('css')
    <style>
        .profile-image {
            width: 85% !important;
            /*height: 120px;*/
            object-fit: cover;
        }
    </style>
@endpush
@section('content')
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="">
                <div class="">
                    <div class="m-portlet">
                        <div class="container">
                            <div class="m-portlet__body">
                                <div class="serviceBoxMain">
                                    <div class="serverInnerDetails">
                                        <div class="row ">
                                            <div class="col-md-12 col-sm-12 col-xs-12 text-right mt-20 moreBtns">
                                                <a href="{{ route('customer.update.password') }}"
                                                   class="btn buttonMain hvr-bounce-to-right">Reset
                                                    Password</a>
                                                <a href="{{ route('customer.update.phone') }}"
                                                   class="btn buttonMain hvr-bounce-to-right">Update
                                                    Phone
                                                    Number</a>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-12 bannerFields">
                                                <form method="post" enctype="multipart/form-data" id="submit-image"
                                                      action="javascript:void(0)">
                                                    <h4>Account Profile &nbsp;
                                                        @csrf
                                                        <input type="hidden" name="user_id" id="user_id"
                                                               value="{{ $user->id}}">

                                                        <label for="image">
                                                            <img src="http://goo.gl/pB9rpQ"
                                                                 style="width: 40px;cursor: pointer;"/>
                                                        </label>

                                                        <input type="file" name="image" id="image" style="display: none"
                                                               onchange="readURL(this);"
                                                               accept=".png, .jpg, .jpeg"/>

                                                    </h4>
                                                </form>
                                                <table cellpadding="0" cellspacing="0" width="100%">
                                                    <tbody>
                                                    <tr>
                                                        <td><img class="profile-image"
                                                                 src="{{$user->profile_pic}}"
                                                                 alt="{{$user->profile_pic}}">
                                                        </td>
                                                        <td width="30%">
                                                            <strong>{{ $user->fullName() }} </strong>
                                                            @if(!is_null($user->membershipDiscount))
                                                                <span style="color: red">{{ ucfirst($user->membershipDiscount->name) }}</span>

                                                            @endif

                                                            <span>{{ $user->email ?? '--' }}</span>
                                                            <span>{{ $user->phone_number ?? '--' }}</span>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                                <br>
                                                <h4>General Profile &nbsp; <a
                                                        href="{{ route('customer.profile.edit') }}"
                                                        class=""><i class="fa fa-pencil-alt"></i></a></h4>
                                                <table cellpadding="0" cellspacing="0" width="100%">
                                                    <tbody>
                                                    <tr>
                                                        <td><strong>GENDER</strong></td>
                                                        <td>{{ ucfirst($user->gender) ?? '--' }}</td>

                                                    </tr>
                                                    <tr>
                                                        <td><strong>ADDRESS</strong></td>
                                                        <td>{{ $user->address .', '. $user->area->name .', '. $user->city->name ?? '--' }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>CNIC</strong></td>
                                                        <td>{{ $user->cnic ?? '--' }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td><strong>AGE</strong></td>
                                                        <td>{{ $user->age ?? '--' }}</td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        function readURL(input, id) {
            ;
            if (input.files && input.files[0]) {


                var formData = new FormData($('#submit-image')[0]);
                $.ajax({
                    type: "POST",
                    url: "{{ route('customer.profile.edit.image') }}",
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        toastr[response.status](response.message);
                        window.location.reload();
                    },
                    error: function () {
                        toastr['error']("Something Went Wrong.");
                    }
                });

                // reader.readAsDataURL(input.files[0]);
                // }
            }
        }
    </script>
@endpush