routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('/', function () {
//    return view('Auth');
//});
//Route::middleware(['private-directory'])->group(function () {
//    Route::get('/welcome','WelcomeController@index')->name('index');
Route::get('/', 'WelcomeController@index')->name('index');
//});

Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
//    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});

//Route::middleware(['private-directory'])->group(function () {
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('/family-friend/register/{referral_code?}', 'Auth\RegisterController@joinAsFamilyFriend')->name('register.family.friend');
Route::post('register', 'Auth\RegisterController@register')->name('register.client');
Route::post('otp/register', 'Auth\RegisterController@otp')->name('otp.register.send');
Route::post('verify/otp/register', 'Auth\RegisterController@verifyOTP')->name('verify.otp.register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::post('otp', 'Auth\ForgotPasswordController@otp')->name('otp.send');
Route::post('verify/otp', 'Auth\ForgotPasswordController@verifyOTP')->name('verify.otp');
Route::post('forgot-password-request', 'Auth\ForgotPasswordController@ForgotPasswordRequest')->name('otp.password.reset');

Route::get('/home', 'HomeController@index')->name('home');
//});

Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/meta-tags', 'Backend\MetaTagController', [
            'only' => ['index', 'create', 'store', 'edit', 'update']
        ]);
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/areas', 'Backend\AreaController');
        Route::post('/areas/import/file', 'Backend\AreaController@importFile')->name('area.import.excel');
        Route::resource('/users', 'Backend\UserController');
        Route::resource('/staffs', 'Backend\StaffController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');
        Route::resource('/category', 'Backend\CategoryController');
        Route::resource('/services', 'Backend\ServiceCategoryController');
        Route::resource('/menu-items', 'Backend\SubCategoryController');
        Route::resource('/addons', 'Backend\AddOnsController');
        Route::resource('/packages', 'Backend\DealController');
        Route::resource('/special-offers', 'Backend\BlogController');
        Route::resource('/faqs', 'Backend\FaqController');
        Route::resource('/comissions', 'Backend\CommisionsController');
        Route::resource('/category-blogs', 'Backend\BlogCategoryController');
        Route::resource('/testimonial', 'Backend\TestimonialController', [
            'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
        ]);
        Route::resource('/banner', 'Backend\BannerController', [
            'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
        ]);
        Route::resource('/managing-parteners', 'Backend\ManagingPartenerController');
        Route::resource('/membership-details', 'Backend\MembershipDetailsController', [
            'only' => ['index', 'store']
        ]);
        Route::resource('/memberships', 'Backend\MembershipController', [
            'only' => ['index', 'edit', 'update']
        ]);

        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/aboutus', 'Backend\AboutUsController', [
            'only' => ['index', 'store']
        ]);


        Route::get('/discounts', 'Backend\DiscountController@index')->name('discount.index');
        Route::resource('/coupons', 'Backend\CouponController');

        Route::resource('/first-order-discount', 'Backend\FirstOrderDisountController', [
            'only' => ['edit', 'update']
        ]);

        Route::resource('/memberships-discount', 'Backend\MembershipDisountController', [
            'only' => ['edit', 'update']
        ]);

        Route::resource('/referral-discount', 'Backend\ReferralDisountController', [
            'only' => ['edit', 'update']
        ]);

        Route::get('/user-referrals', 'Backend\ReferralController@index')->name('user.referral.index');

        //User Order History

        Route::get('/order-history', 'Backend\OrderController@index')->name('get.order.history');
        Route::get('/order/create', 'Backend\OrderController@create')->name('order.create');
        Route::post('/order/store', 'Backend\OrderController@store')->name('order.store');
        Route::get('/order/{id}', 'Backend\OrderController@showOrder')->name('get.user.order.show');
        Route::get('/order/edit/{id}', 'Backend\OrderController@editOrder')->name('get.user.order.edit');
        Route::post('/order/update', 'Backend\OrderController@updateOrder')->name('order.update');
        Route::get('/order/delete/{id}', 'Backend\OrderController@destroy')->name('get.user.order.delete');
        Route::post('/order/updatepayment', 'Backend\AjaxController@updatePaymentStatus')->name('order.updatePaymentStatus');
        Route::post('/order/uploadpaymentslipbyadmin', 'Backend\OrderController@uploadpaymentslipbyadmin')->name('order.uploadpaymentslipbyadmin');


        //Assign Driver

        Route::get('/driver', 'Backend\StaffController@index')->name('get.employee.user');


        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);

        Route::resource('/termsandconditions', 'Backend\TermsAndConditionController', [
            'only' => ['index', 'store']
        ]);

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');

        Route::resource('/ledger', 'Backend\LedgerController');
        Route::resource('/wallet', 'Backend\WalletController');
        Route::resource('/notification', 'Backend\NotificationController');
        Route::get('/staff_order/{id}', 'Backend\WalletController@staffOrder')->name('get.user.staffOrder');

        Route::post('/storepayment', 'Backend\WalletController@storepayment')->name('storepayment');
        Route::resource('/payment', 'Backend\PaymentController');
        Route::post('/providerpaymentverify', 'Backend\AjaxController@providerpaymentverify')->name('providerpaymentverify');
    });
    //route for referral code
    Route::get('/referral-code', 'Backend\SendReferralCodeController@index')->name('referral-code.index');
    Route::post('/referral-code/send', 'Backend\SendReferralCodeController@sendCodeWithEmail')->name('referral-code.send');
    Route::get('/sendsms/{phone}/{message}', 'Backend\SendReferralCodeController@sendCodeWithPhone');


    //Customer Routes
    Route::prefix('customer')->name('customer.')->group(function () {
        Route::get('/dashboard', 'Customer\MainController@index')->name('dashboard.index');
        Route::post('/coupons', 'Customer\CouponController@store')->name('coupons.store');
        Route::delete('/coupons', 'Customer\CouponController@destroy')->name('coupons.destroy');


        //User Profiles
        Route::get('profile', 'Customer\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Customer\ProfileController@editProfile')->name('profile.edit');

app/Models/Area.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    protected $table = 'areas';
    protected $guarded = [];

    public function city(){
        return $this->belongsTo(City::class, 'city_id', 'id');
    }
}

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Aboutus;
use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        $aboutus = Aboutus::first();
        return view('backend.aboutus.create', compact('aboutus'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'summary' => 'required',
            'description' => 'required',
        ], [
            'summary.required' => 'Summary is required.',
            'description.required' => 'Description is required.'
        ]);
        $aboutus = Aboutus::findOrFail(1);

        $aboutus->update([
            'summary' => $request->summary,
            'description' => $request->description
        ]);
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'About us description updated successfully.'
        ]);
    }
}

app/Http/Controllers/Backend/AddOnsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\ServiceCategory;
use App\Models\SubCategory;
use App\Models\AddOn;
use Illuminate\Http\Request;

class AddOnsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $service_sub_categories_addons = AddOn::orderBy('id', 'DESC')->get();

        return view('backend.service_sub_category_addons.index', compact('service_sub_categories_addons'));
    }

    public function create()
    {
        $services = Category::all();
        $service_sub_categories = SubCategory::all();
        return view('backend.service_sub_category_addons.create', compact('service_sub_categories', 'services'));

    }

    public function show($id)
    {

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'                       => 'required',
            'slug'                       => 'required',
            'service_id'                 => 'required',
            'service_category_id' => 'required',
            'service_sub_category_id' => 'required'
        ], [
            'service_id.required' => 'ServiceCategory is required.',
            'service_category_id.required' => 'Category is required.',
            'service_sub_category_id.required' => 'Sub ServiceCategory is required.'
        ]);
        AddOn::create([
            'name' => $request->get('name'),
            'slug' => $request->get('slug'),
            'category_id' => $request->get('service_id'),
            'service_category_id' => $request->get('service_category_id'),
            'service_sub_category_id' => $request->get('service_sub_category_id'),
            'price' => $request->get('price')
        ]);
        return redirect()->route('admin.addons.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Addons created successfully.'
            ]);

    }

    public function edit($id)
    {
        $service_sub_category_addon = AddOn::find($id);
        $service_sub_categories = SubCategory::where('id', $service_sub_category_addon->service_sub_category_id)->get();
        $categories = Category::all();
        $services = ServiceCategory::where('id', $service_sub_category_addon->service_category_id)->get();
        return view('backend.service_sub_category_addons.edit', compact('service_sub_category_addon', 'service_sub_categories', 'categories', 'services'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
            'service_id' => 'required',
            'service_category_id' => 'required',
            'service_sub_category_id' => 'required'
        ], [
            'service_id.required' => 'ServiceCategory is required.',
            'service_category_id.required' => 'Category is required.',
            'service_sub_category_id.required' => 'Sub ServiceCategory is required.'
        ]);
        AddOn::find($id)->update([
            'name' => $request->get('name'),
            'slug' => $request->get('slug'),
            'category_id' => $request->get('service_id'),
            'service_category_id' => $request->get('service_category_id'),
            'service_sub_category_id' => $request->get('service_sub_category_id'),
            'price' => $request->get('price')
        ]);
        return redirect()->route('admin.addons.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Addons updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $service_sub_category_addons = AddOn::findOrFail($id);
        $service_sub_category_addons->delete();

        return redirect()->route('admin.addons.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Addons has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/BlogCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\BlogCategory;
use Illuminate\Http\Request;

class BlogCategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $blog_categories = BlogCategory::orderBy('id', 'DESC')->get();

        return view('backend.category-blogs.index', compact('blog_categories'));
    }

    public function create()
    {
        return view('backend.category-blogs.create');

    }

    public function show($id)
    {

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required|unique:blog_categories,slug',
        ]);
        BlogCategory::create([
            'name' => $request->name,
            'slug' => $request->slug,
        ]);
        return redirect()->route('admin.category-blogs.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Blog ServiceCategory created successfully.'
            ]);

    }

    public function edit($id)
    {
        $blog_category = BlogCategory::find($id);
        return view('backend.category-blogs.edit', compact('blog_category'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);
        $category = BlogCategory::find($id);
        $category->update([
            'name' => $request->name,
            'slug' => $request->slug,
        ]);

        return redirect()->route('admin.category-blogs.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Blog ServiceCategory updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $blog_category = BlogCategory::findOrFail($id);

        $blog_category->blogs()->delete();
        $blog_category->delete();

        return redirect()->route('admin.category-blogs.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Blog ServiceCategory has been deleted'
            ]);
    }
}

resources/views/backend/areas/create.blade.php
@extends('layouts.master')

@section('title','Area')
@section('content')

    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">{{ __('Areas') }}</h3>
            </div>
        </div>
    </div>
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Add {{ __('Area') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.areas.store') }}"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">


                                    <div class="form-group row">


                                        <div class="col-md-6">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Area Name') }} <span class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{{ old('name') }}"
                                                   autocomplete="name" autofocus>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="slug"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Slug') }} <span class="mandatorySign">*</span></label>
                                            <input id="slug" type="text"
                                                   class="form-control @error('slug') is-invalid @enderror"
                                                   name="slug" value="{{ old('slug') }}"
                                                   autocomplete="slug" autofocus>

                                            @error('slug')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>


                                    <div class="form-group row">

                                        <div class="col-md-6">
                                            <label for="city_id"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('City') }} <span class="mandatorySign">*</span></label>

                                            <select id="city_id"
                                                    class="form-control @error('city_id') is-invalid @enderror"
                                                    name="city_id" autocomplete="city_id">
                                                <option value="">Select an option</option>
                                                @foreach($cities as $city)
                                                    <option value="{{$city->id}}">{{$city->name}}</option>
                                                @endforeach
                                            </select>

                                            @error('city_id')
                                            <span class="invalid-feedback" role="alert">
                                                 <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-6">
                                            <label for="price"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Price') }} <span class="mandatorySign">*</span></label>
                                            <input id="price" type="number"
                                                   class="form-control @error('price') is-invalid @enderror"
                                                   name="price" value="{{ old('price') }}"
                                                   min="0" onkeypress="return event.charCode >= 48"
                                                   autocomplete="price" autofocus>

                                            @error('price')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>


                                    </div>

                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.areas.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script>
        $('#name').focusout(function () {

            var name = $(this).val();
            name = name.replace(/\s+/g, '-').toLowerCase();

            $('#slug').val(name);
        })
    </script>
@endpush

resources/views/backend/areas/index.blade.php
@extends('layouts.master')
@section('title','Area')
@push('css')
    <style>
        .form-group {
            margin-bottom: 0;
        }
    </style>
@endpush
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Areas
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('admin.areas.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Area</span>
                                </span>
                            </a>
                        </li>


                        <li class="m-portlet__nav-item">


                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <form action="{{ route('admin.area.import.excel') }}" method="post"
                              enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <div class="col-md-6">

                                    <input type="file" name="file" class=" form-control">
                                </div>
                                <div class="col-md-6">
                                    <button type="submit"
                                            class="btn btn-success m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                        Upload
                                        File
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th> Sr NO.</th>
                        <th> Name</th>
                        <th> Price</th>
                        <th> Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($areas))
                        @foreach($areas as $area)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$area->name}}</td>
                                <td>{{$area->price}}</td>
                                <td nowrap>
                                    <a href="{{route('admin.areas.edit',$area->id)}}"
                                       class="btn btn-sm btn-info pull-left ">Edit</a>
                                    <form method="post" action="{{ route('admin.areas.destroy', $area->id) }}"
                                          id="delete_{{ $area->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <a style="margin-left:10px;" class="btn btn-sm btn-danger m-left"
                                           href="javascript:void(0)"
                                           onclick="if(confirmDelete()){ document.getElementById('delete_<?=$area->id?>').submit(); }">
                                            Delete
                                        </a>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "columnDefs": [
                {orderable: false, targets: [3]}
            ],
        });
    </script>
@endpush